// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";
const lovableAuth = createLovableAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple" | "microsoft" | "lovable", opts?: SignInOptions) => {
      // First try standard Supabase direct OAuth for supported providers
      if (provider === "google" || provider === "apple") {
        try {
          const { data, error } = await supabase.auth.signInWithOAuth({
            provider: provider,
            options: {
              redirectTo: opts?.redirect_uri,
            },
          });
          if (!error && data?.url) {
            return { redirected: true, url: data.url };
          }
          if (error) {
            console.warn("[OAuth] Supabase OAuth error:", error);
          }
        } catch (e) {
          console.warn("[OAuth] Supabase OAuth exception:", e);
        }
      }

      // Fallback to Lovable Cloud Auth if available
      try {
        const result = await lovableAuth.signInWithOAuth(provider, {
          redirect_uri: opts?.redirect_uri,
          extraParams: {
            ...opts?.extraParams,
          },
        });

        if (result.redirected) {
          return result;
        }

        if (result.error) {
          return result;
        }

        try {
          await supabase.auth.setSession(result.tokens);
        } catch (e) {
          return { error: e instanceof Error ? e : new Error(String(e)) };
        }
        return result;
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
    },
  },
};
